/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicPublicRouteImport } from './routes/_public/public'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthGuideRouteImport } from './routes/_auth/guide'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPublicRoute = PublicPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => PublicRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthGuideRoute = AuthGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof AuthGuideRoute
  '/login': typeof GuestLoginRoute
  '/public': typeof PublicPublicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof AuthGuideRoute
  '/login': typeof GuestLoginRoute
  '/public': typeof PublicPublicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/guide': typeof AuthGuideRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_public/public': typeof PublicPublicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/login' | '/public'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide' | '/login' | '/public'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_public'
    | '/_auth/guide'
    | '/_guest/login'
    | '/_public/public'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/public': {
      id: '/_public/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicPublicRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/guide': {
      id: '/_auth/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthGuideRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthGuideRoute: typeof AuthGuideRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuideRoute: AuthGuideRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface PublicRouteChildren {
  PublicPublicRoute: typeof PublicPublicRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPublicRoute: PublicPublicRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
